import type { Metadata } from 'next'
import './globals.css'
import Navigation from './[components]/Navigation'
import AuthProvider from './[components]/AuthProvider'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

        <AuthProvider>
        <body className='bg-gray-100'>
        <Navigation/>
        <div className='m-2'></div>
        {children}
                
        </body>
        </AuthProvider>


    </html>
  )
}
